### PR TITLE
Add Scrutinizer, Editorconfig, & Travis coverage

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
Let me know if I'm imposing my workflow on you, but this adds some of the tools I use to help me keep aligned with a standard. The only thing is WPCS calls for tabs, not spaces, so I can change .editorconfig to match that if you prefer spaces.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Errgh, yeah, so if you prefer spaces, this probably isn't the best way to do this. Or I can switch everything. Or define our own. Or just add editorconfig and use scrutinizer as a guide.

**Comment by benbalter** [comment]
> Errgh, yeah, so if you prefer spaces, this probably isn't the best way to do this. Or I can switch everything to tabs. Or define our own standards. Or just add editorconfig and use scrutinizer as a guide.

I believe PHP (and WordPress) prefers tabs. If I used spaces, it's only because I had my editor set for Ruby (which I use primarily at work).

**Comment by benbalter** [comment]
> Let me know if I'm imposing my workflow on you,

Not at all! :smile:

**Comment by benbalter** [comment]
@mAAdhaTTah Added you as a collaborator. For anything other than irrefutable changes, if you could continue using pull requests (even if from one branch to another within the repo), it'd allow myself and others to weigh in more easily.

**Comment by mAAdhaTTah** [comment]
> I believe PHP (and WordPress) prefers tabs. If I used spaces, it's only because I had my editor set for Ruby (which I use primarily at work).

I'll add a scrutinizer/whitespace commit at the end of #42.

> For anything other than irrefutable changes, if you could continue using pull requests (even if from one branch to another within the repo), it'd allow myself and others to weigh in more easily.

No problem. Happy to help.

**Pull request merged**
