### PR TITLE
[NEEDS FEEDBACK] Add initial activation notice

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
Closes (?) #14. We can't suggest an initial import/export on activation, but we can let the user know what to do. Not sure if this is the best message, feel free to suggest alternatives.

### CODE REVIEW

**Comment by benbalter** [comment]
Can you talk a bit through your option/transient logic? I'm not able to grok the intended behavior from the code alone.

**Comment by mAAdhaTTah** [comment]
It's cuz of the way plugin activation goes. The [codex explains it](https://codex.wordpress.org/Function_Reference/register_activation_hook#Process_Flow) but the short version is there's an activation then a redirect, so in order to display the message, we have to store something (using a transient in this case) so that when the plugin page loads, it reads from there and displays the admin notice.

**Comment by benbalter** [comment]
> It's cuz of the way plugin activation goes.

Ugh. I forgot about that. You're right. Makes sense. :+1:

**Comment by mAAdhaTTah** [comment]
Any thoughts on the copy?

**Pull request merged**
