### PR TITLE
add German translation

### PR DESCRIPTION
**Pull request by lsinger**

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Thank you so much for this! I'll definitely merge this in as-is, but there are going to be some changes in the translation strings in the next version. Would you be open to me reaching out after the next release for an updated translation?

**Comment by lsinger** [comment]
@mAAdhaTTah sure thing, just ping me! :smile:

**Comment by mAAdhaTTah** [comment]
@lsinger Just released a new version if you'd like to update your translations. Thanks!

**Comment by lsinger** [comment]
PR submitted!

**Pull request merged**
