### PR TITLE
Set composer type to wordpress-plugin

### LINKED ISSUE #17: Vendor SPYC via Composer

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
Fixes #17.

This fixes the composer.json file for managing sites with composer. This would send the plugin into the proper plugin direction, which requires composer/installers.

You could also register this on packagist now too.

I'm also wondering why we're installing a package we depend on but aren't using it from that location. We can set that package's install directory to the location it's supposed to be in, if you want as well.

### CODE REVIEW

**Comment by benbalter** [comment]
> I'm also wondering why we're installing a package we depend on but aren't using it from that location. We can set that package's install directory to the location it's supposed to be in, if you want as well.

Can you expand on that a bit? Are you talking about `spyc` in `lib`? If so, that's a mistake with the Composer file (believe this was my first Composer project at the time). Would :heart: your help getting it fixed up.

**Comment by mAAdhaTTah** [comment]
So we've got two options:

1. We can basically leave it as-is and load Spyc from it's current location. We don't necessarily need a composer.json to load it, and if you merge this as-is (although you could delete the require block), this will allow you to register the plugin on Packagist so those of us who manage their site with composer can pull it in from there (which would make it available primarily to developers who, I presume, would understand ).
2. We can switch to managing that dependency with composer. We should remove it from version control and pull it in via composer. If you're managing your WordPress site with composer, the dependency will get pulled in and it'll work fine, but deploying to wordpress.org will be a bit more complicated, and you then have to perform a build process before committing to svn.

If you think we'll end up with additional dependencies, managing them with composer is way easier. If not, it won't be worth the extra build step.

I can fix if you let me know which direction you want to go in.

**Comment by benbalter** [comment]
I'm leaning towards option #2, just to keep Spyc up to date, but would it be possible to commit the code to version control so that it'd work on .org installs? Although atypical, would composer realize the code is there on install and simply skip it?

**Comment by mAAdhaTTah** [comment]
No, that's wouldn't work exactly, because if someone is managing their plugins/wordpress site via composer, it'll install and load up the dependency in the user's vendor folder, and then it would be pulled in and loaded up again when you fire up the plugin and Fatal Error out.

**Comment by benbalter** [comment]
Huh. Okay. I'd rather optimize for doing things "right", so I think option 2 makes the most sense, and I can write a quick script to vendor the spyc code prior to pushing to wordpress.org.

**Comment by mAAdhaTTah** [comment]
That would work. I'll move everything around properly and update this PR.

**Comment by mAAdhaTTah** [comment]
Updated. Just note the current version breaks when using WP-CLI, as WP-CLI actually bundles Spyc as well, so our usage double-loads it and Fatal Errors out. I've opened a PR to fix this issue with them:

https://github.com/mustangostang/spyc/pull/42

**Comment by benbalter** [comment]
:metal: Thanks for working through this with me. 

> I've opened a PR to fix this issue with them:

Ha. That actually fixes an issue with https://github.com/benbalter/wordpress-to-jekyll-exporter. Thanks again!

**Pull request merged**
