### PR TITLE
Whitelisted filter and fix a typo

### PR DESCRIPTION
**Pull request by WellingGuzman**

### CODE REVIEW

**Comment by WellingGuzman** [comment]
@mAAdhaTTah this commit [6080e75](https://github.com/benbalter/wordpress-github-sync/commit/6080e751f49a27dc0da9b0ec90992f43ce657c1c) I believe it makes it easier to use the filter, this way it can be used on `functions.php` after the plugin is been loaded.

Let me know what you think.

**Comment by mAAdhaTTah** [comment]
I'm of two minds about that, between enforcing best practices and playing into user expectations.

1. The filter to add post_types/statuses shouldn't really be added in functions.php, as it's theme-related and doesn't pertain to the display of the site. Additionally, switching themes means you lose those functions. The documentation suggests creating an `mu-plugin` (https://github.com/benbalter/wordpress-github-sync/commit/0557f1e6cb6a5f46a4b9f8b22781248cf2d858ce) which won't get lost if the user decides to switch themes. Forcing them into an `mu-plugin` (because it simply won't work) is actually better for them (plus you don't have to run the filter every time you use it, which is slightly better performance-wise).

2. However, it is extremely common for plugins to suggest to their users to add something to `functions.php` while `mu-plugins` are definitely less common. I don't know how much confusion could arise from this, but I wouldn't expect every, or even most, users to have an `mu-plugins` folder. Maybe we could presume a slightly higher level of knowledge b/c they're GitHub users, but not by much.

Would appreciate any thoughts. cc @benbalter 

The other two commits look good though.

**Comment by mAAdhaTTah** [comment]
Actually, I think I'm going to go with this. We'll recommend mu-plugins but refusing to support alternate methods is silly.

**Comment by WellingGuzman** [comment]
@mAAdhaTTah about `sanitize_text_field` I read it's not necessary because `wp_insert_post` does it anyway, so it's safe to use unsanitized strings. [post.php#L3078](https://core.trac.wordpress.org/browser/tags/4.1.2/src/wp-includes/post.php#L3078)

Referring to the using it on `functions.php` this not strong suggesting to use it on `functions.php` but rather be used anywhere, because it's call it after the plugin is loaded. I'm not saying what you think is not the best way, but letting the filter being used anywhere, In other word: another option.

**Comment by WellingGuzman** [comment]
@mAAdhaTTah The thing what I think it's better to use `array_key_exists` it's because: we want to unset the key if exists, not only when has a valid value (non null, falsy).

for example here:
```php
if ( isset( $meta['ID'] ) ) {
	$args['ID'] = $meta['ID'];
	unset( $meta['ID'] );
}

foreach ( $meta as $key => $value ) {
	update_post_meta( $post_id, $key, $value );
}
```
When there's not ID, it would create a meta value for that `post_id` called **ID** because it hasn't been unset because it was false, empty or whatever.

Another thing I found now, it's that this could throw an `Undefined index` Notice if the `layout` and `published` index is not set on YAML.
```php
// Before
$args['post_type'] = $meta['layout'];
unset( $meta['layout'] );

$args['post_status'] = true === $meta['published'] ? 'publish' : 'draft';
unset( $meta['published'] );


// After
if ( array_key_exists( 'layout', $meta ) {
	$args['post_type'] = $meta['layout'];
	unset( $meta['layout'] );
}

if ( array_key_exists( 'published', $meta ) ) {
	$args['post_status'] = true === $meta['published'] ? 'publish' : 'draft';
	unset( $meta['published'] );
}
```
And we can let WordPress set the `post_type` and `post_status`.

I'd create another commit for this one, unless you do it before me.

**Comment by mAAdhaTTah** [comment]
> Referring to the using it on functions.php this not strong suggesting to use it on functions.php but rather be used anywhere, because it's call it after the plugin is loaded. I'm not saying what you think is not the best way, but letting the filter being used anywhere, In other word: another option.

Yeah, you're right :).

> The thing what I think it's better to use array_key_exists it's because: we want to unset the key if exists, not only when has a valid value (non null, falsy).

Yeah, I think you're right about this too. I'm assuming too much about the content that's coming in. All it really needs to be imported is empty frontmatter, so a user could create a file that looks like this:

```md
---
---
I just wrote a post.
```

And it'll get imported. If we're going to allow that, then after import, WPGHS needs to push out the updated data. The problem is right now the controller is too convoluted to do this effectively, so that would require a major refactor to that working, which is in the cards, but I kinda want to punt that until after 1.0.0.

Not that this affects this PR, but I'll note in the docs that importing a new post from GitHub is not yet supported.

**Comment by mAAdhaTTah** [comment]
+1 this looks good, thanks for your help.

**Pull request merged**
