### PR TITLE
Export posts as cronjob

### LINKED ISSUE #35: Export to GitHub times out
I'm getting 504 Gateway errors on Nginx trying to export my whole blog to set up the plugin. Maybe we should do this in batches via AJAX?

Also, would the GitHub endpoint support us pushing multiple files in a single call, or do we have to make an individual call for each file?

Lastly, I'm not sure the post_lock set up you have works the way you think it does. If there are two separate requests exporting at the same time, each runtime environment isn't crossing into each other, so if two different people are exporting, they can do so at the same time, regardless of whether the post_lock is set. I think it needs to be persisted somewhere, like an option or transient, that's set up and deleted before each request.

I can break these into 3 different issues; the first one is the only one I'm sure needs to be addressed.

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
Fixes #35.

I'm still occasionally getting sync errors errors, but those are distinct from the timeout errors I reported earlier.

### CODE REVIEW

**Comment by benbalter** [comment]
@mAAdhaTTah this looks great. Quick question for my own knowledge: How does moving to cron affect the timeout? E.g., does the cron job not have a PHP-level timeout?

**Comment by mAAdhaTTah** [comment]
In all honesty, this is the first time I've implemented something this way. What I do know is it runs as a background task, meaning it doesn't delay the loading of the page that it's kicked off on.

We could do something like export 10 posts, save the remaining, and rekickoff our cronjob again with `spawn_cron` over and over until it's complete, if we want to get around the timeout question. That'll kick off a new process.

**Comment by mAAdhaTTah** [comment]
A friend of mine says there is a php-level timeout on cron tasks.

**Comment by mAAdhaTTah** [comment]
This works. This will make it easier to solve that exporting bug I'm running into.

**Comment by benbalter** [comment]
Thanks!

**Pull request merged**
